import type { DepartmentBudget } from './types';

export const MOCK_DEPARTMENT_BUDGETS: DepartmentBudget[] = [
  {
    id: 'dept-eng',
    departmentName: 'Engineering & Infrastructure',
    departmentCode: 'ENG',
    managerName: 'Alex Rivera',
    totalLimit: 250000,
    totalSpent: 187500,
    totalRemaining: 62500,
    asset: 'USDC',
    period: 'monthly',
    updatedAt: new Date().toISOString(),
    agents: [
      {
        id: 'agent-1',
        agentId: 'agt-soroban-relayer',
        agentName: 'Soroban Relayer Sentinel',
        role: 'Contract Deployment & Gas Relayer',
        allocatedAmount: 100000,
        spentAmount: 82000,
        remainingAmount: 18000,
        asset: 'USDC',
        velocity24h: 3400,
        lastTransactionAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
        ledger: [
          { id: 'ldg-1a', date: new Date(Date.now() - 1000 * 60 * 12).toISOString(), description: 'Soroban gas relay top-up', counterparty: 'Stellar Network', amount: 3400 },
          { id: 'ldg-1b', date: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(), description: 'Contract deployment batch #482', counterparty: 'Soroban Testnet', amount: 12800 },
          { id: 'ldg-1c', date: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), description: 'RPC node relayer fees', counterparty: 'Stellar Network', amount: 4650 },
        ],
      },
      {
        id: 'agent-2',
        agentId: 'agt-ci-bot',
        agentName: 'CI/CD Automated Tester',
        role: 'Stellar Sandbox Test Runner',
        allocatedAmount: 80000,
        spentAmount: 64500,
        remainingAmount: 15500,
        asset: 'USDC',
        velocity24h: 1800,
        lastTransactionAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        ledger: [
          { id: 'ldg-2a', date: new Date(Date.now() - 1000 * 60 * 45).toISOString(), description: 'CI runner minutes — sandbox suite', counterparty: 'GitHub Actions', amount: 1800 },
          { id: 'ldg-2b', date: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(), description: 'Nightly regression test compute', counterparty: 'Stellar Sandbox', amount: 5200 },
        ],
      },
      {
        id: 'agent-3',
        agentId: 'agt-infra-monitor',
        agentName: 'RPC Health Monitor Agent',
        role: 'Telemetry & Pinging',
        allocatedAmount: 70000,
        spentAmount: 41000,
        remainingAmount: 29000,
        asset: 'USDC',
        velocity24h: 950,
        lastTransactionAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
        ledger: [
          { id: 'ldg-3a', date: new Date(Date.now() - 1000 * 60 * 5).toISOString(), description: 'RPC ping monitoring — 24h window', counterparty: 'Horizon RPC', amount: 950 },
          { id: 'ldg-3b', date: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(), description: 'Latency alerting infra', counterparty: 'Stellar Network', amount: 2100 },
        ],
      },
    ],
  },
  {
    id: 'dept-mktg',
    departmentName: 'Growth & Liquidity Marketing',
    departmentCode: 'MKTG',
    managerName: 'Elena Rostova',
    totalLimit: 150000,
    totalSpent: 67500,
    totalRemaining: 82500,
    asset: 'USDC',
    period: 'monthly',
    updatedAt: new Date().toISOString(),
    agents: [
      {
        id: 'agent-4',
        agentId: 'agt-amm-arb',
        agentName: 'Soroban DEX Arbitrageur',
        role: 'Liquidity Provisioning',
        allocatedAmount: 90000,
        spentAmount: 42000,
        remainingAmount: 48000,
        asset: 'USDC',
        velocity24h: 2100,
        lastTransactionAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
        ledger: [
          { id: 'ldg-4a', date: new Date(Date.now() - 1000 * 60 * 20).toISOString(), description: 'DEX liquidity rebalance', counterparty: 'Soroswap AMM', amount: 2100 },
          { id: 'ldg-4b', date: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(), description: 'Arbitrage sweep — XLM/USDC pair', counterparty: 'Soroswap AMM', amount: 9400 },
        ],
      },
      {
        id: 'agent-5',
        agentId: 'agt-campaign',
        agentName: 'Airdrop Campaign Bot',
        role: 'Micropayment Distribution',
        allocatedAmount: 60000,
        spentAmount: 25500,
        remainingAmount: 34500,
        asset: 'USDC',
        velocity24h: 1200,
        lastTransactionAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
        ledger: [
          { id: 'ldg-5a', date: new Date(Date.now() - 1000 * 60 * 180).toISOString(), description: 'Airdrop batch — community wave 12', counterparty: 'Community Distribution', amount: 1200 },
        ],
      },
    ],
  },
  {
    id: 'dept-ops',
    departmentName: 'Treasury & Operations',
    departmentCode: 'OPS',
    managerName: 'Marcus Vance',
    totalLimit: 500000,
    totalSpent: 410000,
    totalRemaining: 90000,
    asset: 'XLM',
    period: 'monthly',
    updatedAt: new Date().toISOString(),
    agents: [
      {
        id: 'agent-6',
        agentId: 'agt-sweep-bot',
        agentName: 'Auto-Sweep Treasury Bot',
        role: 'Wallet Consolidation',
        allocatedAmount: 300000,
        spentAmount: 260000,
        remainingAmount: 40000,
        asset: 'XLM',
        velocity24h: 15000,
        lastTransactionAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
        ledger: [
          { id: 'ldg-6a', date: new Date(Date.now() - 1000 * 60 * 2).toISOString(), description: 'Wallet consolidation sweep — batch 91', counterparty: 'Treasury Vault', amount: 15000 },
          { id: 'ldg-6b', date: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(), description: 'Idle balance sweep — sub-wallets', counterparty: 'Treasury Vault', amount: 42000 },
        ],
      },
      {
        id: 'agent-7',
        agentId: 'agt-payroll',
        agentName: 'Stellar Payroll Executor',
        role: 'Automated Contractor Disbursements',
        allocatedAmount: 200000,
        spentAmount: 150000,
        remainingAmount: 50000,
        asset: 'XLM',
        velocity24h: 8000,
        lastTransactionAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
        ledger: [
          { id: 'ldg-7a', date: new Date(Date.now() - 1000 * 60 * 360).toISOString(), description: 'Contractor payroll run — August cycle', counterparty: 'Payroll Batch', amount: 8000 },
          { id: 'ldg-7b', date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), description: 'Contractor payroll run — July cycle', counterparty: 'Payroll Batch', amount: 79500 },
        ],
      },
    ],
  },
  {
    id: 'dept-ai',
    departmentName: 'AI Research & Model Inference',
    departmentCode: 'AIR',
    managerName: 'Dr. Sarah Chen',
    totalLimit: 100000,
    totalSpent: 92000,
    totalRemaining: 8000,
    asset: 'ASTRO',
    period: 'monthly',
    updatedAt: new Date().toISOString(),
    agents: [
      {
        id: 'agent-8',
        agentId: 'agt-nim-briefing',
        agentName: 'Nvidia NIM Analyst Agent',
        role: 'Financial Intelligence Briefings',
        allocatedAmount: 60000,
        spentAmount: 56000,
        remainingAmount: 4000,
        asset: 'ASTRO',
        velocity24h: 4200,
        lastTransactionAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
        ledger: [
          { id: 'ldg-8a', date: new Date(Date.now() - 1000 * 60 * 8).toISOString(), description: 'Daily financial intelligence briefing run', counterparty: 'Nvidia NIM', amount: 4200 },
          { id: 'ldg-8b', date: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(), description: 'Model inference credits top-up', counterparty: 'Nvidia NIM', amount: 18500 },
        ],
      },
      {
        id: 'agent-9',
        agentId: 'agt-risk-eval',
        agentName: 'Realtime Risk Modeler',
        role: 'Policy Evaluation & Fraud Detection',
        allocatedAmount: 40000,
        spentAmount: 36000,
        remainingAmount: 4000,
        asset: 'ASTRO',
        velocity24h: 2300,
        lastTransactionAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      },
    ],
  },
];
